CREATE SEQUENCE IF NOT EXISTS chat_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS mesaj_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS consultatie_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS fisier_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS notificare_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS plata_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS recenzie_id_seq START 1;
CREATE SEQUENCE IF NOT EXISTS video_id_seq START 1;

